CREATE TABLE allseasons(
    id INT PRIMARY KEY,
    player_name varchar(50),
    team_abbreviation VARCHAR(10),
    age FLOAT,
    player_height FLOAT,
    player_weight FLOAT,
    college VARCHAR(50),
    country VARCHAR(50),
    draft_year VARCHAR(50),
    draft_round VARCHAR(50),
    draft_number VARCHAR(50),
    games_played FLOAT,
    points_per_game FLOAT,
    rebound FLOAT,
    assist_per_game FLOAT,
    net_rating FLOAT,
    offensive_rebound_pct FLOAT,
    defensive_rebound_pct FLOAT,
    usage_pct FLOAT,
    true_shooting_pct FLOAT,
    assist_pct FLOAT,
    season VARCHAR(20)
);